### ISSUE TITLE
Mexican test suite

### ISSUE THREAD

**Issue by matin** [cuenca-mx/arcus-python#7]
Similar to this: https://github.com/cuenca-mx/regalii-certifier/blob/master/tests/test_mexican_suite.py

- [ ] authentication #11 
- [ ] account #12
- [ ] billers #13
- [ ] cancel bill #8 
- [ ] bills #15 
- [ ] payment for a bill #16
- [ ] list of bill payments #17
- [ ] cambiar métodos de pago #18

**Comment by felipaoo** [comment]
done
